### ISSUE TITLE
Support pack command

### ISSUE THREAD

**Issue by GeertvanHorrik** [Philo/cake-npm#10]
I am trying to generate an npm package using cakebuild. I am nearly there, and would like to add this support to this package.

We can do a few things:

1. Add the pack command to this library, then I will call it myself
2. Copy most of my code (which also does the copy/paste from a specific directory, updates the version, then packs it (still requires 1 though).

What's the easiest?

**Comment by Philo** [comment]
If you are in a position to create a pull request that includes this functionality I would be help with review and merge it into Cake.Npm, otherwise if you can give me a brief summary of the functionality you would need I will endeavour to implement it when I next have an opportunity.
