### ISSUE TITLE
Npm Logging Level

### ISSUE THREAD

**Issue by gep13** [Philo/cake-npm#15]
I have only just started using this Addin, so I could be missing something REALLY obvious, but...

When I use this Addin to do an NPM install of a tool that is required in my Cake Build, the resulting logs in my AppVeyor window become almost unusable, as they are populated with multiple warnings, which actually show up as red error text in AppVeyor.

Have a look here:

https://ci.appveyor.com/project/cakebuild/cake-vso/build/0.3.0-unstable.16.build.21#L132

As an example.

Is there anything that can be done about this?  Thanks!

/cc @Philo @agc93

**Comment by agc93** [comment]
@gep13 Have you tried replacing:

```
Npm.Install(settings => settings.Package("tfx-cli").Globally());
```
with
```
Npm.WithLogLevel(NpmLogLevel.Warn).Install(settings => settings.Package("tfx-cli").Globally());
```

(be careful about #13 if you're using experimental mode).

That should at least quieten down the output a bit. Not exactly sure why AppVeyor is picking the execution up as a `NativeCommandError` like that..

**Comment by Philo** [comment]
@gep13 - When I added the logging features I wanted to provide a one-to-one mapping between the cake logging level and the npm logging level, little did I know the sheer volume of stuff logged with some of the NPM log levels, I usually run the install like this:

```c#
Npm.WithLogLevel(NpmLogLevel.Silent).FromPath(".").Install();
```

In order to quiet down NPM.  I plan on re-visiting the loglevel translation when I next get some time for OS work.

**Comment by gep13** [comment]
@agc93 @Philo thank you both.  I will give the suggestions a try, and see how I get on.

**Comment by agc93** [comment]
@gep13 Did you have a chance to try those different settings? I just checked one of my VSTS builds and noticed the same npm-output-shown-as-error effect you were getting, but without the weird line-breaking behaviour

![screenshot 79](https://cloud.githubusercontent.com/assets/1369269/18622015/dc2b75f4-7e6d-11e6-893c-56e9bdf20739.png)

**Comment by gep13** [comment]
@agc93 @Philo sorry, I should have closed the loop on this one...

Yes, using the suggestions above, I was able to get a much more readable output in the log:

https://ci.appveyor.com/project/cakebuild/cake-vso/build/0.3.0-unstable.24.build.27

Thanks!
