### ISSUE TITLE
add support for specifying location of package.json for npm installation step

### ISSUE THREAD

**Issue by Philo** [Philo/cake-npm#3]
From discussion in #2
```c#
.Package(DirectoryPath path)
.Package(FilePath path)
```

**Comment by nengberg** [comment]
Don't you think that another name than `Package` would be more suitable. What I have done now is a method called `.FromPath(string)`.

Example: `Npm.Install(settings => settings.FromPath("path_to_package_json"));`

Then you could do something like:

`Npm.Install(settings => settings.FromPath("path_to_package_json").Package("gulp"));`

Which then installs gulp from the path given. What do you think?

**Comment by Philo** [comment]
Just understanding how this needs to work and looking at the npm install docs.

```npm install``` needs to be executed in the directory containing package.json, you cant do ```npm install ./other_dir/package.json```.  In this case the addin current directory will need to be altered for the npm process during execution to support this?

Is this how you are implementing the ```.FromPath()``` setting?

I would also suggest that you the option takes a ```DirectoryPath``` instead of a string.  Cake has implicit conversions from string to DirectoryPath and the method arguments intent will be more descriptive.

**Comment by nengberg** [comment]
Yeah this is a tricky one...

Currently I am doing exactly what you're saying - changing the directory during execution and then changing it back. I don't know if thats optimal or if it even fits in this module.

**Comment by andymac4182** [comment]
Is there an example of how to change working dir? I can't seem to find one in the docs for CAKE.

**Comment by nengberg** [comment]
@andymac4182: I have a fix for this in a fork which I am using for different projects. As it is not officially supported by npm itself it is a work around to adjust current directory before the command is executed. I can open a PR if @Philo don't mind?

**Comment by andymac4182** [comment]
That would be great if you could even publish the branch. We have our files a few levels deep in the repo below the cake file so this would be a big help.

**Comment by nengberg** [comment]
I'll look into that tomorrow!

**Comment by nengberg** [comment]
@andymac4182: Here you have my branch: https://github.com/nengberg/cake-npm/tree/feature/custom-path-for-npm-install

This allow us to specify `Npm.Install(settings => settings.FromPath("../another-path-to-package-json"));`

**Comment by hoest** [comment]
Hi,

Would love to see this change being merged soon!

**Comment by Philo** [comment]
If @nengberg can open a pull request for his update I can look at getting it merged

**Comment by Philo** [comment]
I have updated Cake.Npm to support specifying the working directory for tool execution:

- The Npm cake alias now supports the ```.FromPath(DirectoryPath)``` to set the
  working directory for the subsequent npm commands
- ```.FromPath(DirectoryPath)``` must be the first action after ```Npm.```
- Adds support for chaining npm commands, see usage.cake for example

```c#
 Npm.FromPath("./usage")
   .Install(settings => settings.Package("gulp").Globally())
   .Install(settings => settings.Package("another-package"))
   .RunScript(...);
```

The update has been released to nuget as a prerelease package initially, the existing usage patterns all remain so will be no issues with backwards compatibility however would like to get some feedback from users before pushing the release out as v0.7.0

The prerelease version can be tested using the below addin syntax

```c#
#addin nuget:?package=Cake.Npm&prerelease
```

Hopefully this will also address #8 and #9

**Comment by nengberg** [comment]
That seems like a nice solution! I tried to use the prerelease just to verify that my build still works as expected but I'm getting this: `Error: System.MissingMethodException: Method not found: 'Cake.Core.Tooling.IToolLocator Cake.Core.ICakeContext.get_Tools()'.`

**Comment by Philo** [comment]
@nengberg, you will need to ensure that you have also updated to cake 0.13.0.  Check/delete your tools directory and ensure you are using the latest bootstrapper from https://github.com/cake-build/resources.

**Comment by nengberg** [comment]
Thanks @Philo. It works like a charm :)

**Comment by Philo** [comment]
I'll update the readme, but I'm happy to ignore adding tests for the working directory setup, as that is a feature coming from Cake itself, Cake.Npm is just overriding a method from the ```Tool``` base class and that is only being accessed within the ```RunProcess``` method.

**Comment by nengberg** [comment]
Fair enough!
