### ISSUE TITLE
Add support for run-script commands

### ISSUE THREAD

**Issue by wvandrunen** [Philo/cake-npm#5]
My project has a bunch of them defined in the packages.json and I'm not able to execute them with the install command alone. https://docs.npmjs.com/cli/run-script. I'll fix it in my fork and create a PR.

**Comment by Philo** [comment]
@wvandrunen 

A PR with your additional features will be greatly appreciated, as my initial use case for this addin was simply to execute client side build steps via gulp I focused on the `install` command.

**Comment by agc93** [comment]
@Philo @wvandrunen I've opened PR #6 to add basic run-script command support. Hopefully it works for you @wvandrunen ..
