### ISSUE TITLE
How to implement directory switching

### ISSUE THREAD

**Issue by agc93** [Philo/cake-npm#9]
This is in relation to #3 and #8  in particular. The `Tool<T>` class now has a `GetWorkingDirectory` method that can be used to "natively" switch directory a given tool. My thinking is rather than baking it just in to the `Install` or `RunScript` command, we could add it at an alias level.

Currently, `Npm` is a `CakePropertyAlias`, but if we add a `CakeMethodAlias` that takes a `Path` as a parameter, it could apply no matter the command. Syntax would be something like:

```
//for the default (current behaviour)
Npm.RunScript("test");
Npm.Install();

// or to operate on another directory
Npm("./path/to/package.json").RunScript("test");
Npm("./path/to/package/dir").Install();
```

That way, we can pass the path straight to `NpmRunner` and have access, no matter what command we're running.

Thoughts @Philo , @nengberg  or anyone else?

**Comment by agc93** [comment]
You can see a basic support [in my fork](https://github.com/agc93/cake-npm/tree/feature/working-directory)

**Comment by Philo** [comment]
I've implemented a way to specify the working directory for Npm commands, see #3 for more info

**Comment by agc93** [comment]
Ah that's awesome @Philo
